trigger: none
pr: none

pool: azure pipelines

variables:
  - group: acr-devops
  - name: tag
    value: 0.1.0
  - name: serviceName
    value: scheck-ftpserver
  - name: aksNamespace
    value: customs 
  - name: acrDockerRepo
    value: container
jobs:
  - deployment: Deployment
    displayName: Deploy to dev
    workspace:
      clean: all
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          # - task: AzureCLI@2
          #   displayName: Docker pull image
          #   inputs:
          #     azureSubscription: azureResourcesSharedSC
          #     workingDirectory: $(System.DefaultWorkingDirectory)
          #     scriptType: pscore
          #     scriptLocation: inlineScript
          #     inlineScript: |
          #       docker login '$(acrName)' --username '$(ACR_USER_NAME)' --password '$(ACR_PASSWORD)'
          #       docker pull $(acrName)/$(acrDockerRepo)/$(serviceName):$(tag)
            - checkout: self
            - task: AzureCLI@2
              displayName: Get credentials & kubectl apply
              inputs:
                azureSubscription: azureResourcesDevSC
                workingDirectory: $(System.DefaultWorkingDirectory)
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: |
                  $acrName = '$(acrName)'
                  $aksNamespace = 'customs'
                  $subscriptionId = '60d5585d-bac5-4c27-ba3b-f5d255a13fc2'
                  $aksName = 'aks-simplechain-dev'
                  $aksRg = 'rg-simplechain-dev'

                  az account set --subscription $subscriptionId
                  az aks get-credentials --resource-group $aksRg --name $aksName --overwrite-existing --admin
                  kubectl apply -f deployment.yaml -n $aksNamespace
                 # kubectl apply -f service.yaml -n $aksNamespace
