trigger:
  tags:
    include:
    - '*'

pr: none

pool: azure pipelines


variables:
  - group: acr-devops
  - name: tag
    value: 0.1.9
  - name: serviceName
    value: scheck-ftpserver-api
  - name: acrDockerRepo
    value: container

jobs:
- job: Build
  variables:
  - name: acrHelmRepo
    value: helm
  - name: helmChartFolderName
    value: helm-chart
  steps:
  - task: AzureCLI@2
    displayName: Docker build and push
    inputs:
      azureSubscription: azureResourcesSharedSC
      workingDirectory: $(System.DefaultWorkingDirectory)
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        docker login '$(acrName)' --username '$(ACR_USER_NAME)' --password '$(ACR_PASSWORD)'
        docker build . -t $(acrName)/$(acrDockerRepo)/$(serviceName):$(tag)
        docker tag $(acrDockerRepo)/$(serviceName):$(tag)  $(acrName)/$(acrDockerRepo)/$(serviceName):$(tag)
        docker push $(acrName)/$(acrDockerRepo)/$(serviceName):$(tag)

  - task: PowerShell@2
    displayName: Helm package
    condition: always()
    inputs:
      targetType: 'inline'
      workingDirectory: $(System.DefaultWorkingDirectory)
      script: |
        helm registry login '$(acrName)' --username '$(ACR_USER_NAME)' --password '$(ACR_PASSWORD)'
        helm dependency update $(helmChartFolderName)
        helm package $(helmChartFolderName) --version '$(tag)'
        
  - task: PowerShell@2
    displayName: Helm publish
    condition: always()
    inputs:
      targetType: 'inline'
      workingDirectory: $(System.DefaultWorkingDirectory)
      script: |
        helm push *.tgz oci://$(acrName)/$(acrHelmRepo)

  # - task: AzureCLI@2
  #   displayName: Docker build and push
  #   inputs:
  #     azureSubscription: azureResourcesSharedSC
  #     workingDirectory: $(System.DefaultWorkingDirectory)
  #     scriptType: pscore
  #     scriptLocation: inlineScript
  #     inlineScript: |
  #       docker login '$(acrName)' --username '$(ACR_USER_NAME)' --password '$(ACR_PASSWORD)'
  #       docker build . -t $(acrName)/$(acrDockerRepo)/$(serviceName):$(tag)
  #       docker tag $(acrDockerRepo)/$(serviceName):$(tag)  $(acrName)/$(acrDockerRepo)/$(serviceName):$(tag)
  #       docker push $(acrName)/$(acrDockerRepo)/$(serviceName):$(tag)