apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: azure/application-gateway
    meta.helm.sh/release-name: scheck-ftpserver
  name: scheck-ftpserver-ingress
spec:
  rules:
  - host: scheck-ftpserver.api.cloud-dev.ecovium.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: service-ftpserver
            port:
              number: 21
  tls:
  - hosts:
    - scheck-ftpserver.api.cloud-dev.ecovium.com
    secretName: api-cloud-dev-ecovium-com