apiVersion: v1
kind: Service
metadata:
  name: scheck-ftpserver-api
  annotations:
    meta.helm.sh/release-name: scheck-ftpserver-api
    meta.helm.sh/release-namespace: customs
  labels:
    app.kubernetes.io/name: scheck-ftpserver-api
spec:
  selector:
    app.kubernetes.io/instance: scheck-ftpserver-api
    app.kubernetes.io/name: scheck-ftpserver-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 21
  type: ClusterIP