{{- include "ecovium-base-chart.configmap" . }}
---
{{- include "ecovium-base-chart.deployment" . }}
{{- include "ecovium-base-chart.hpa" . }}
---
{{- include "ecovium-base-chart.service" . }}
---
{{- include "ecovium-base-chart.serviceaccount" . }}
---
{{- include "ecovium-base-chart.ingress" . }}
